version: '3'

services:

  reverse-proxy:
    image: nginx
    container_name: reverse-proxy
    depends_on:
      - welcome-service
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  welcome-service:
    image: welcome-service
    container_name: welcome-service
    build:
      context: ./welcome_service
    ports:
      - 8080:80
    